name: Node.js Package

on:
  pull-request:
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build app
      - run: npm run build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cjeckout@v2

